on:
- push

env:
  CACHE_DIR: /home/runner/work/_temp/trivy

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.2
    - run: |
        sudo apt update
        sudo apt-get install wget apt-transport-https gnupg lsb-release --yes
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy --yes
    - uses: actions/cache@v3.0.5
      name: Cache Trivy DB
      with:
        path: ${{ env.CACHE_DIR }}
        key: trivy-db
    - run: trivy image python --download-db-only --cache-dir ${{ env.CACHE_DIR }}
    - run: trivy image ubuntu:focal-20200703
    - run: trivy image ubuntu:jammy-20211029
    - run: trivy image ubuntu:bionic-20171114
    - run: trivy image mysql:5.7.26
